### ISSUE TITLE
Failed to launch Qcm after the recent upgrade of qt6

### ISSUE THREAD

**Issue by Integral-Tech** [hypengw/Qcm#10]
After the recent upgrade of qt6 (6.5.3 -> 6.6.0), Qcm failed to start.

![Screenshot_20231013_111128](https://github.com/hypengw/Qcm/assets/71180087/590cc677-8b22-43b6-a1b5-3f3d46d284e5)

---
- OS: Arch Linux, rolling
- DE: KDE Plasma 5.27.8
- WM: KWin (Wayland)

**Comment by hypengw** [comment]
Fixed.
