### ISSUE TITLE
我喜爱的歌单无法使用

### ISSUE THREAD

**Issue by hundan2015** [hypengw/Qcm#13]
提示
![image](https://github.com/hypengw/Qcm/assets/12100012/ab5d8e21-55c5-497d-bd74-8a3287ee0bd8)

**Comment by hyhcrh** [comment]
Some of my playlists also don't work with the same error.
I can't find the common features in these playlists.

**Comment by hyhcrh** [comment]
qcm更新到了1.02（来自aur）
我喜爱的歌单和其他部分歌单仍然无法使用，提示：
![图片](https://github.com/hypengw/Qcm/assets/76899134/519d705e-13a0-4755-a7e5-d85a448fa3b1)

**Comment by hypengw** [comment]
用 aur 的 .git 包测试一下

**Comment by hyhcrh** [comment]
刚刚安装了qcm-git，和qcm一样的错误

**Comment by hyhcrh** [comment]
> 刚刚安装了qcm-git，和qcm一样的错误



> 用 aur 的 .git 包测试一下

刚刚安装了qcm-git，和qcm一样的错误

**Comment by hypengw** [comment]
可以的话，用网页或者手机看一下第 199 的歌，然后发一下分享链接
还有 aur 的 git 包需要切到最新的 commit

**Comment by hyhcrh** [comment]
刚刚手动git clone和makepkg -si了，问题解决
