### ISSUE TITLE
[BUG]Open custom music list Error

### ISSUE THREAD

**Issue by thmiku** [hypengw/Qcm#15]
ERROR error:
    [json.exception.type_error.302] (/playlist/tracks/389/cf) type must be string, but is null(1) at ncm::api_model::parse<PlaylistDetail>(std::span<const std::byte>)::<lambda(auto:68)>::<lambda(auto:69)> [with auto:69 = qcm::json::Error] /home/riku/Public/Extrapkg/qcm/src/Qcm/service/ncm/include/ncm/api.h(101:35) at /home/riku/Public/Extrapkg/qcm/src/Qcm/build/app/app_autogen/JQV2N6Y3RS/../../../../app/include/Qcm/api.h(172:17)

**Comment by hypengw** [comment]
fixed.
