### ISSUE TITLE
Wish: UI Optimization for Plasma Mobile

### ISSUE THREAD

**Issue by Integral-Tech** [hypengw/Qcm#16]
I installed Qcm 1.0.1 from flatpak on Plasma Mobile. However, the UI is not fully optimized for phone screen.

![Screenshot_20240301_211423](https://github.com/hypengw/Qcm/assets/71180087/0926bd46-a498-4768-be1a-f47d5314900a)
![Screenshot_20240301_211455](https://github.com/hypengw/Qcm/assets/71180087/3c75e07a-6a91-4846-8f48-3449487b28b7)
![Screenshot_20240301_211436](https://github.com/hypengw/Qcm/assets/71180087/01439361-efae-43ce-b088-b54a928c6fca)

**Comment by hypengw** [comment]
finished.
