### ISSUE TITLE
Back button/Tabs disappear in portrait mode

### ISSUE THREAD

**Issue by Guanran928** [hypengw/Qcm#25]
I use Qcm on postmarketOS (Linux on mobile  phones), which does not have a back button or physical keyboard.

Back button/Tabs disappear in portrait mode in some pages, which makes it impossible to navigate on mobile devices.

Example screenshot:

![image](https://github.com/hypengw/Qcm/assets/68757440/6ccef1e6-6041-4281-b270-7e0b3de87f5a)

**Comment by hypengw** [comment]
Added.

**Comment by Guanran928** [comment]
Thanks!
