### ISSUE TITLE
[bug]更新后出现问题

### ISSUE THREAD

**Issue by Hitagi-Hu** [hypengw/Qcm#35]
1.最大化窗口时，左边侧栏是展开的，无法折叠回去
2.点击应用偶尔需要两次甚至多次才能启动

版本：1.10
仓库：flatpak
系统信息：fedora40 x86_64
linux内核：6.10
桌面：gnome 46.5

**Comment by Hitagi-Hu** [comment]
补充：
1.窗口最大化时，左侧少了"meau"这个折叠按钮
2.偶尔第一次点击打开应用，会卡在不完整的转圈圈的启动动画然后闪退，再次打开就能成功启动。在我电脑上发生的频率不低。

**Comment by hypengw** [comment]
```bash
flatpak install io.github.hypengw.Qcm.Debug
flatpak run --devel --command=bash io.github.hypengw.Qcm
[📦 io.github.hypengw.Qcm ~]$ gdb Qcm
(gdb) run
Enable debuginfod for this session? (y or [n]) n

# when crash
(gdb) bt
```

**Comment by hypengw** [comment]
然后把 bt 后的输出贴一下

> 1.窗口最大化时，左侧少了"meau"这个折叠按钮

设计就是这样的，最大化时 drawer 已经展开到窗口了

**Comment by Hitagi-Hu** [comment]
> ```shell
> flatpak install io.github.hypengw.Qcm.Debug
> flatpak run --devel --command=bash io.github.hypengw.Qcm
> [📦 io.github.hypengw.Qcm ~]$ gdb Qcm
> (gdb) run
> Enable debuginfod for this session? (y or [n]) n
> 
> # when crash
> (gdb) bt
> ```

#0  0x00007ffff2d85555 in QCoreApplicationPrivate::lockThreadPostEventList(QObject*) ()
    at /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#1  0x00007ffff2dd5c5d in QObject::deleteLater() () at /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#2  0x00007ffff65893a7 in qcm::Global::set_session (this=<optimized out>, val=<optimized out>)
    at /run/build/Qcm/qcm_interface/global.cpp:255
#3  0x00005555555ca5b1 in operator() (ok=<optimized out>, __closure=<optimized out>)
    at /run/build/Qcm/app/src/action.cpp:97
#4  tl::detail::invoke<qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::operator()(qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::_ZZN3qcm3App15on_load_sessionEPNS_5model7SessionEENKUlvE_clEv.Frame*)::<lambda(bool)>, bool&> (f=<optimized out>)
    at /run/build/Qcm/third_party/expected/include/tl/expected.hpp:298
#5  tl::detail::expected_map_impl<tl::expected<bool, error::Error>&, qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::operator()(qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::_ZZN3qcm3App15on_load_sessionEPNS_5model7SessionEENKUlvE_clEv.Frame*)::<lambda(bool)>, 0>
    (f=<optimized out>, exp=...)
    at /run/build/Qcm/third_party/expected/include/tl/expected.hpp:2117
#6  tl::expected<bool, error::Error>::transform<qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::operator()(qcm::App::on_load_session(qcm::model::Session*)::<lambda()>::_ZZN3qcm3App15on_load_sessionEPNS_5model7SessionEENKUlvE_clEv.Frame*)::<lambda(bool)> >
    (f=<optimized out>, this=0x5555568966e0)
    at /run/build/Qcm/third_party/expected/include/tl/expected.hpp:1383
#7  operator()(_ZZN3qcm3App15on_load_sessionEPNS_5model7SessionEENKUlvE_clEv.Frame *)
    (frame_ptr=0x555556896690) at /run/build/Qcm/app/src/action.cpp:93
--Type <RET> for more, q to quit, c to continue without paging--

**Comment by hypengw** [comment]
fixed: https://github.com/hypengw/Qcm/commit/b7bf7824028bcc87566359aadcaa5572a29b1ec5
