### ISSUE TITLE
Arch Linux. 编译后深色主题和图标出现问题

### ISSUE THREAD

**Issue by Kimiblock** [hypengw/Qcm#4]
- 深色模式无法切换, 报错 `qrc:/QcmApp/qml/page/MainPage.qml:132: TypeError: Cannot assign to read-only property "theme"`
![Screenshot_20230502_192136](https://user-images.githubusercontent.com/61745317/235652713-beff57d7-7404-4473-b7f8-678e51590ed2.png)

- 图标位置不正.
![Screenshot_20230502_192811](https://user-images.githubusercontent.com/61745317/235653895-15b60c39-f7b3-449d-abd6-8e49544a4208.png)

以上两个问题在 Flatpak 中均无法复现, 打包脚本在 [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qcm-git). 麻烦作者指出编译打包中存在的问题.

**Comment by hypengw** [comment]
> 图标位置不正.

qt6.5 的 material 组件大改了，我需要适配一下
